src/Entity/Reclamation.php
<?php

namespace App\Entity;

use App\Repository\ReclamationRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ReclamationRepository::class)
 */
class Reclamation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank(message="This field should not be blank nor null")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="This field should not be blank nor null")
     */
    private $problem;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getProblem(): ?string
    {
        return $this->problem;
    }

    public function setProblem(string $problem): self
    {
        $this->problem = $problem;

        return $this;
    }

    public function __toString():string{
        return $this->title;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

templates/FrontOffice/baseUser.html.twig
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>eLEARNING - eLearning HTML Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{{asset('FrontOffice/img/favicon.ico')}}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{{ asset('FrontOffice/lib/animate/animate.min.css')}}" rel="stylesheet">
    <link href="{{ asset('FrontOffice/lib/owlcarousel/assets/owl.carousel.min.css')}}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{{ asset('FrontOffice/css/bootstrap.min.css')}}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{{asset('FrontOffice/css/style.css')}}" rel="stylesheet">
    <link href="{{asset('css/profile.css')}}" rel="stylesheet">
</head>

<body>
<!-- Spinner Start -->
<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>
<!-- Spinner End -->


<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg bg-dark navbar-light shadow sticky-top p-0">
    <a href="index.html" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
        <h2 class="m-0 text-primary"> <img style="height: 50px;width: 50px" class="" src="{{ asset('BackOffice/images/boxBG.png') }}" /><img  style="height: 50px;width: 200px" src="{{ asset('BackOffice/images/logo.png') }}"></h2>
    </a>
    <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            <a href="index.html" class="nav-item nav-link active">Home</a>
            <a href="about.html" class="nav-item nav-link active">About</a>
            <a href="courses.html" class="nav-item nav-link active">Courses</a>
            {% if app.user %}
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle active" data-bs-toggle="dropdown">Reclamation</a>
                <div class="dropdown-menu fade-down m-0">
                    <a href="{{ path('add_reclamation') }}" class="dropdown-item">Add reclamation</a>
                    <a href="{{ path('reclamation') }}" class="dropdown-item">My reclamations</a>
                </div>
            </div>
            {% endif %}
            <a href="contact.html" class="nav-item nav-link active">Contact</a>
        </div>

        {% if not app.user %}
            <a href="{{ path('login') }}" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Join Now<i class="fa fa-arrow-right ms-3"></i></a>
        {% else %}
            <div style="float:right" class="nav-item dropdown bg-dark  d-none d-lg-block" style="width: auto">
                <div  style="float: right; width: auto;" class="d-flex">
                    <p style="margin-top: 15px;margin-left: 50px">{{ app.user.username }}</p>
                    {% if app.user.image %}
                        <img style="height: 50px;width: 50px;border-radius: 50%;object-fit: cover; margin-left: 20px; margin-right: 5px" src="{{ asset('uploads/images/profiles/'~ app.user.image) }}"/>
                    {% else %}
{#                        <i style="margin-left: 20px; margin-right: 5px" class="fa fa-user fa-3x" style="border-radius: 25%" aria-hidden="true"></i>#}
                        <img style="height: 50px;width: 50px;border-radius: 50%;object-fit: cover; margin-left: 20px; margin-right: 5px" src="https://img.icons8.com/officel/100/000000/user.png"/>
                    {% endif %}
                </div>
                <div class="dropdown-menu fade-down m-0">
                    <a href="{{ path('profile') }}" class="dropdown-item">Profile</a>
                    <a href="{{ path('logout') }}" class="dropdown-item">Logout</a>
                </div>
            </div>
        {% endif %}
    </div>
</nav>
<!-- Navbar End -->
{% block body %}
{% endblock %}
<!-- Footer Start -->
<div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-3">Quick Link</h4>
                <a class="btn btn-link" href="">About Us</a>
                <a class="btn btn-link" href="">Contact Us</a>
                <a class="btn btn-link" href="">Privacy Policy</a>
                <a class="btn btn-link" href="">Terms & Condition</a>
                <a class="btn btn-link" href="">FAQs & Help</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-3">Contact</h4>
                <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                <div class="d-flex pt-2">
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-3">Gallery</h4>
                <div class="row g-2 pt-2">
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="{{asset('FrontOffice/img/course-1.jpg')}}" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="{{ asset('FrontOffice/img/course-2.jpg') }}" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="{{asset('FrontOffice/img/course-3.jpg')}}" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="{{asset('FrontOffice/img/course-2.jpg')}}" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="{{asset('FrontOffice/img/course-3.jpg')}}" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="{{asset('FrontOffice/img/course-1.jpg')}}" alt="">
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-3">Newsletter</h4>
                <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                <div class="position-relative mx-auto" style="max-width: 400px;">
                    <input class="form-control border-0 w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                    <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="copyright">
            <div class="row">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved.

                    <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                    Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a><br><br>
                    Distributed By <a class="border-bottom" href="https://themewagon.com">ThemeWagon</a>
                </div>
                <div class="col-md-6 text-center text-md-end">
                    <div class="footer-menu">
                        <a href="">Home</a>
                        <a href="">Cookies</a>
                        <a href="">Help</a>
                        <a href="">FQAs</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->


<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>


<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{{asset('FrontOffice/lib/wow/wow.min.js')}}"></script>
<script src="{{asset('FrontOffice/lib/easing/easing.min.js')}}"></script>
<script src="{{asset('FrontOffice/lib/waypoints/waypoints.min.js')}}"></script>
<script src="{{asset('FrontOffice/lib/owlcarousel/owl.carousel.min.js')}}"></script>

<!-- Template Javascript -->
<script src="{{asset('FrontOffice/js/main.js')}}"></script>
{% block js %}
{% endblock %}
</body>

</html>

templates/FrontOffice/modifyProfile.html.twig
{% extends 'FrontOffice/baseUser.html.twig' %}
{% block body %}
    <div style="height: 70vh; width: 100%; padding: 50px">


        {{ form_start(form) }}
        <div class="form-group">
            <label>Username</label>
            {{ form_widget(form.username,{'attr': {'placeholder':'Username.','class':'form-control'}}) }}
        </div>
        <div class="form-group">
            <label>Email</label>
            {{ form_widget(form.email,{'attr': {'placeholder':'Entre your email here.','class':'form-control'}}) }}
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Profile Picture</label>
            {{ form_widget(form.imageFile,{'attr': {'class':'form-control'}}) }}
        </div>
        <div class="form-group">
            <label >Phone</label>
            {{ form_widget(form.Telephone,{'attr': {'placeholder':'Enter your phone here.','class':'form-control'}}) }}
        </div>
        <div class="form-group">
            <label >Address</label>
            {{ form_widget(form.address,{'attr': {'placeholder':'Enter your address here.','class':'form-control'}}) }}
        </div>

        <button style="float: right; margin: 20px" type="submit" class="btn btn-primary">Submit</button>
        {{ form_end(form) }}


    </div>
{% endblock %}

templates/FrontOffice/profile.html.twig
{% extends 'FrontOffice/baseUser.html.twig' %}
{% block body %}

    <div class="page-content p-5" id="content">
        <div>
            <div style="position: absolute;right: 10px;top: 20px ;margin-right: 30px;">
                <img src="" alt="" style="margin-top: -10px;height: 100px;">
            </div>
            <h1>Profile</h1>

            <hr>
        </div>
        <div class="container">
            <div class="row gutters" >
                <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12"  >
                    <div class="card h-100" >
                        <div class="card-body" style="box-shadow: 5px 5px 15px 5px rgba(0,0,0,0.2);">
                            <div class="account-settings">
                                <div class="card-body">
                                    <div class="d-flex flex-column align-items-center text-center">
                                        {% if user.image %}
                                            <img style="height: 100px;width: 100px;border-radius: 50%;object-fit: cover;" src='{{ asset('uploads/images/profiles/'~ app.user.image) }}' width="65" class="mr-3 rounded-circle img-thumbnail ">

                                        {% else %}
                                            <img src="https://img.icons8.com/officel/100/000000/user.png"/>
                                        {%endif%}
                                        <div class="mt-3">
                                            <h4 style="text-transform: capitalize;">{{ user.username }}</h4>
                                            <p class="text-secondary mb-1">
                                                {% if user.roles[0]=="ROLE_USER" %}
                                                    Simple User
                                                {% else %}
                                                    Admin
                                                {% endif %}
                                            </p>
                                            <a  href="{{ path('modify_profile') }}" class="btn btn-outline-primary" href="">Modifier</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
                    <div class="card h-100">
                        <div class="card-body" style="box-shadow: 5px 5px 15px 5px rgba(0,0,0,0.2);">
                            <div class="row">
                                <div class="card-body">
                                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                        <h6 class="mb-3 text-primary">Info personnelle</h6>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-3">
                                            <h6 class="mb-0">Nom et prénom</h6>
                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                            {{ user.username }}
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="row">
                                        <div class="col-sm-3">
                                            <h6 class="mb-0">Email</h6>
                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                            {{ user.email }}
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="row">
                                        <div class="col-sm-3">
                                            <h6 class="mb-0">Telephone</h6>
                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                            {% if user.Telephone %}
                                            {{ user.Telephone }}
                                            {% else %}
                                            Empty
                                            {% endif %}

                                        </div>
                                    </div>
                                    <hr>
                                    <div class="row">
                                        <div class="col-sm-3">
                                            <h6 class="mb-0">Adresse</h6>
                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                            {% if user.address %}
                                                {{ user.address }}
                                            {% else %}
                                                Empty
                                            {% endif %}
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="row">
                                        <div class="col-sm-3">
                                            <h6 class="mb-0">Is Verified ? </h6>
                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                            {% if user.isVerified %}
                                            Yes
                                            {% else %}
                                            No
                                            {% endif %}
                                        </div>
                                    </div>
                                    <hr>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}